# General
description: We're signposting, sharing knowledge and facilitating conversations across the UK TRE landscape.

# Images
images: [images/uktre-logo.svg, images/github.svg, images/slack.svg, images/community-photo.JPEG]
mainMenuLogo: images/uktre-logo.svg

# Options
options:
  bootStrapJs: true
  breadCrumb: true
  listCategoryFilter: true
  listTagFilter: true